title: Sugandha Saurabh
logo: /assets/img/logo.png
description: Associate Consultant @CGI | Data Science Enthusiast | AI & ML Engineer
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
